<h2>Sign up using this form</h2>

<?php echo $this->tag->form("../login/register"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="price">Role</label>
        <?php echo $this->tag->selectStatic(
        "role",
       [
        "user"=>"User",
        "admin" => "Admin",
        ]
       ); ?>
    </p>
    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>
    
    <p>
    <button type="submit" class="btn btn-primary btn-lg"  name="userlogin"><?php 
                  echo  $this->locale->_('register');
                 ?></button>
       
        <?php echo $this->tag->linkTo(
    'login',
    'Login Here!'
); ?>
    </p>


</form>