<?php
if ($settings->count() > 0) {
    ?>
   
    <a href="#" class="nav-link" id="user" ><h4><?php  echo  $this->locale->_('settings'); ?></h4></a>
    <div id="userdiv">
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            
            <th>Default Price</th>
            <th>Default Stock</th>
            <th>Default Zipcode</th>
            <th>Title Optimization </th>
            
            
            
        </tr>
        </thead>
       
        <tbody>
        <?php foreach ($settings as $setting) { ?>
            <tr>
               
                <td><?php echo $setting->default_price; ?></td>
                <td><?php echo $setting->default_stock ?></td>  
                <td><?php echo $setting->default_zip ?></td> 
               
                <form method="POST" action="settings/changetag" > <td> 
                <select name="title"  onchange='this.form.submit()' >
                <option value="<?php echo $setting->title_opt ?>" name='tags'><?php echo  $setting->title_opt ?> Tags</option>
                <option value="with" name='tags'>With Tags</option>
                <option value="without" name='tags'>Without Tags</option>
               </select>
                  </td>
                 
                </form>
                  
                
                
        <?php } ?>
        </tbody>
    </table>
    </div>

    <?php
}

?>