<?php if($blogs->count()>0){
?>
<div class="bg-image" 
     style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/76.jpg');
            height: 100vh">
            <div class="container">
<div class="mt-3" >
	<div class="row">
	    
	    <div class="col-md-8 col-md-offset-2">
	        
    		<h1>Update post</h1>
    		<?php foreach($blogs as $blog){ ?>
    		<form action="../user/updateblog"  method="POST"> 
            <div class="mb-3">
           <label for="formFile" class="form-label">Title</label>
           <input class="form-control" type="text" id="formFile" name="title" value="<?php echo $blog->title;?>" >
           <input class="form-control" type="hidden" id="formFile" name="updateid" value="<?php echo $blog->blogid;?>" >
           </div>
           <div class="form-group">
    		        <label for="description">Description</label>
    		        <textarea rows="5" class="form-control" name="details" ><?php echo $blog->details;  ?></textarea>
    		    </div>
    		    
    		    <div class="form-group mt-3" >
    		        <button type="submit" class="btn btn-primary" name="btnupdate">
    		          UPDATE BLOG
    		        </button>
    		        
    		    </div>
    		    
    		</form>
            <?php }?>
		</div>
		
	</div>
</div>
</div>


</div>
<?php
}