<?php  if($blogs->count()> 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>BlogId</th>
            <th>Title</th>
            <th>Details</th>
            
           
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Blogs quantity: <?php echo $blogs->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($blogs as $blog) { ?>
            <tr>
                
                <td><?php echo $blog->title; ?></td>
                <td><?php echo $blog->details; ?></td>
               
                <td>
                <form method="POST" action="../user/editblog" ><button name="btnedit" class="btn btn-Warning" value="<?php echo $blog->blogid?>" >Edit</button></form></td>
              
                
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
?>
